package com.briup.apps.dao;

import com.briup.apps.bean.test;
import com.briup.apps.bean.testExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface testMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Wed Nov 13 20:33:23 CST 2019
     */
    long countByExample(testExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Wed Nov 13 20:33:23 CST 2019
     */
    int deleteByExample(testExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Wed Nov 13 20:33:23 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Wed Nov 13 20:33:23 CST 2019
     */
    int insert(test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Wed Nov 13 20:33:23 CST 2019
     */
    int insertSelective(test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Wed Nov 13 20:33:23 CST 2019
     */
    List<test> selectByExample(testExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Wed Nov 13 20:33:23 CST 2019
     */
    test selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Wed Nov 13 20:33:23 CST 2019
     */
    int updateByExampleSelective(@Param("record") test record, @Param("example") testExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Wed Nov 13 20:33:23 CST 2019
     */
    int updateByExample(@Param("record") test record, @Param("example") testExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Wed Nov 13 20:33:23 CST 2019
     */
    int updateByPrimaryKeySelective(test record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table test
     *
     * @mbg.generated Wed Nov 13 20:33:23 CST 2019
     */
    int updateByPrimaryKey(test record);
}